### ISSUE TITLE
The module enables screenshots in non-selected apps

### ISSUE THREAD

**Issue by k2helix** [VarunS2002/Xposed-Disable-FLAG_SECURE#10]
Hi, I just installed this module in LSPosed because I wanted to be able to record an app that normally would not let me do that. However, if I try to take a screenshot of other apps such as Signal (I enabled in its settings to prevent screenshots and recordings) it works when I have not selected that app in the LSPosed module.
Thanks in advance

**Comment by VarunS2002** [comment]
@k2helix 
Sorry for the late response.
Did you try disabling the module from LSPosed and then try again and also restarting every time you change anything in LSPosed?

**Comment by k2helix** [comment]
> @k2helix 
> Sorry for the late response.
> Did you try disabling the module from LSPosed and then try again and also restarting every time you change anything in LSPosed?

@VarunS2002 yup, I tried doing that but I think the module always works for every app.

**Comment by VarunS2002** [comment]
@k2helix 
Some apps need to be enabled to work but others work only if Android System is selected.
Probably that's why.

**Comment by k2helix** [comment]
@VarunS2002 and is there a way to disable the module in those apps that work if Android System is enabled?
I only want the module to be enabled in one app

**Comment by VarunS2002** [comment]
@k2helix 
First to verify what I said I will have to check the log

**Comment by k2helix** [comment]
Here are the logs of the module in LSPosed
![IMG_20211228_123922.jpg](https://user-images.githubusercontent.com/49949593/147562622-4f4db07b-188f-4f6c-b4e8-33e9fe99a6b9.jpg)

**Comment by k2helix** [comment]
@VarunS2002 and here the apps I selected in LSPosed
![Screenshot_20211228-124029_LSPosed.png](https://user-images.githubusercontent.com/49949593/147562693-d06eae3d-0020-4049-871b-60341fc20e82.png)

**Comment by k2helix** [comment]
Ok nevermind, I just disabled the module in System Framework and now it works as intended. Thanks for your support!

**Comment by VarunS2002** [comment]
@k2helix Okay cool!
