### ISSUE TITLE
Bootloop after installing the module and rebooting

### ISSUE THREAD

**Issue by Mino260806** [VarunS2002/Xposed-Disable-FLAG_SECURE#13]
There is nothing I can say more... Device is stuck at MIUI logo, adb doesn't work, there is no way of taking a log...

LSPosed, only selected system framework
My device is Redmi Note 10S with stock MIUI 12.5, A11.

**Comment by VarunS2002** [comment]
@Mino260806 
I understand your concern but without additional information even I can't do anything because I can't test it without that device.
To prevent this from happening in the future I recommend you to use: https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver
