### ISSUE TITLE
Module update required 

### ISSUE THREAD

**Issue by M7amma** [VarunS2002/Xposed-Disable-FLAG_SECURE#14]
I've been usin this module on my banking app (banqumisr) but since their latest update the online banking app doesn't open at all while this module is turned on and the app is hooked by it and displays an error msg abt root detection. When this module turned off, the banking app opens normally.

**Comment by VarunS2002** [comment]
@Marvinoo 
Unfortunately there is nothing I can do about this.
Root cannot be hidden from an app that is hooked by any module. 
This is just how Zygisk works.

The only thing you can try is activating the module only on System Framework and see if screenshots work.
