### ISSUE TITLE
No Screenshot In "Cred" App

### ISSUE THREAD

**Issue by yo-honey** [VarunS2002/Xposed-Disable-FLAG_SECURE#17]
Hi,
Thanks for this module however i wanted to report that this is not working on Cred app,
Cred app will not open if i use this module for Cred app.

Android version 12 OOS.

**Comment by VarunS2002** [comment]
@yo-honey Can you please try activating any other random xposed module on the cred app (and deactivate my app) to see if it still opens?

**Comment by yo-honey** [comment]
No, it's not opening i tried with "killergram" module.

**Comment by VarunS2002** [comment]
> No, it's not opening i tried with "killergram" module.

@yo-honey This means that it checks if you're device is rooted and doesn't open if it is. You cannot hide root from an app if you activate any Xposed module on it. 

Unfortunately, there is nothing I can do about this issue since it's unrelated to my app.
