### ISSUE TITLE
Two modules with nearly same name & versioning!?

### ISSUE THREAD

**Issue by Enkidu70** [VarunS2002/Xposed-Disable-FLAG_SECURE#19]
Meanwhile there are two looking very similar modules:

* https://github.com/LSPosed/DisableFlagSecure

&

* https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE

Are those identical?

If not, could you please add some info what's the difference?

Tnx in advance.

**Comment by VarunS2002** [comment]
> Meanwhile there are two looking very similar modules:
> 
> * https://github.com/LSPosed/DisableFlagSecure
> 
> &
> 
> * https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE
> 
> Are those identical?
> 
> If not, could you please add some info what's the difference?
> 
> Tnx in advance.

Both apps do exactly the same thing and even share code. My app combines code from 3 different apps (including the one you mentioned) that do the same thing into one as none of them seemed to support all apps. I hope this answers your question!

**Comment by Enkidu70** [comment]
> Both apps do exactly the same thing and even share code. My app combines code from 3 different apps (including the one you mentioned) that do the same thing into one as none of them seemed to support all apps. I hope this answers your question!

Thank you very much.

Maybe you can make that important difference a bit more visible? I was confused what app to use. :upside_down_face:

**Comment by VarunS2002** [comment]
> > Both apps do exactly the same thing and even share code. My app combines code from 3 different apps (including the one you mentioned) that do the same thing into one as none of them seemed to support all apps. I hope this answers your question!
> 
> Thank you very much.
> 
> Maybe you can make that important difference a bit more visible? I was confused what app to use. 🙃

Doesn't matter which one you use, try any one and if it works fine then stay on it else try the other.
