### ISSUE TITLE
How do we uninstall Xposed Disable Flag Secure?

### ISSUE THREAD

**Issue by GrayLanterns** [VarunS2002/Xposed-Disable-FLAG_SECURE#21]
Hey, hope you're doing well.

I don't find an app called "Xposed Disable Flag Secure" in my system. Is deleting the apk from file manager is the same as uninstalling the app? Pardon me, I'm a rookie.

PS: Not an issue exactly, but I didn't find a discussion tab on your profile, so I was left with no choice but to ask here.

**Comment by mahmudoloyede** [comment]
Go to all applications in your settings.
The app should be on the list. Click on it and there should be an option to uninstall.

**Comment by souvikmishra** [comment]
The app name would be something like "Disable-FILE SECURE"

**Comment by mahmudoloyede** [comment]
Yes

**Comment by Arafat0010** [comment]
> I don't find an app called "Xposed Disable Flag Secure" in my system. Is deleting the apk from file manager is the same as uninstalling the app?

Yes, you can uninstall it from app manager.
Also you can uninstall it from your LsPosed module manager long press to that module you will get uninstall option.

**Comment by PhDStudentNuSt** [comment]
or from computer OS using `adb uninstall name_of_app`
