### ISSUE TITLE
WhatsApp View Once - Not working

### ISSUE THREAD

**Issue by akhil4755** [VarunS2002/Xposed-Disable-FLAG_SECURE#22]
Couldnt Make it work with WhatsApp View Once photos. Did anyone get it working ? Am I doing something wrong ?

**Comment by Arafat0010** [comment]
> Couldnt Make it work with WhatsApp View Once photos. Did anyone get it working ? Am I doing something wrong ?

No I am facing the same problem too, in my case the module isn’t working in any apps. Showing me a tost notification “ This app doesn’t allow screenshot for pp restrictions”

**Comment by icdmkg2** [comment]
Having the same problem still didnt find any fixes

**Comment by Arafat0010** [comment]
> Having the same problem still didnt find any fixes

And the dev is also not reaponding...☹️

**Comment by VarunS2002** [comment]
@akhil4755 @Arafat0010 @icdmkg2 @krishna1415
Sorry for the very late reply. I have been very busy.
What is the exact issue here?
1. Whatsapp allows you to screenshot but the image is black.
2. Whatsapp does not allow you to take a screenshot at all.

**Comment by akhil4755** [comment]
@VarunS2002 WhatsApp not allowing screenshots ( for view once photos ) . no screenshots at all. not even black screen.

**Comment by icdmkg2** [comment]
@VarunS2002 Whatsapp has a one time picture feature. We tried to bypass the block using the xposed addon and it didnt work

**Comment by VarunS2002** [comment]
@akhil4755 @icdmkg2 
Okay I will look into this. Which Android version and ROM are y'all running?

**Comment by icdmkg2** [comment]
Im running android 13 and samsungs one ui 5.1

**Comment by VarunS2002** [comment]
@akhil4755 @icdmkg2 @Arafat0010 @krishna1415

Seems to be working fine for me. I am running `WhatsApp 2.23.25.83` which is the latest on play store. I tested this on `Samsung's One UI 5.0 based on Android 13`.

https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/assets/30069380/a28b4125-9ad0-4cfd-b36a-98a4c7c88b1f

This means that it is probably a problem with the installation or activation of the module. Why don't y'all send me the module logs  after y'all have already tried reinstalling the module.

**Comment by icdmkg2** [comment]
https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE/assets/87490651/318ae588-debe-48f7-b344-039cc719fab3

Tried it now and it does work

**Comment by akhil4755** [comment]
@VarunS2002 Hi, I was trying to use this mode in LSPatch on a non-rooted OnePlus 8. This wont work using Shuzuku & LSPatch ? 

I found about this in [https://www.youtube.com/watch?v=80cRqjuNF-8] video.

**Comment by icdmkg2** [comment]
> WhatsApp.Video.2023-12-27.at.21.27.00_9bd12d18.mp4 
> Tried it now and it does work

Dosent work**

**Comment by VarunS2002** [comment]
@icdmkg2 @akhil4755 
You guys seem to be using LSPatch.
So this module hooks into Android system and the target app to remove the restrictions. For many apps, just hooking into the targeted app is required (which is what LSPatch does) but for some apps (eg. WhatsApp now), you need to hook into Android System too which LSPatch cannot do and needs root (afaik). There is nothing I can do about this.

**Comment by CCerrer** [comment]
[LSPatch 0.7](https://github.com/JingMatrix/LSPatch/actions/runs/12103943429) managed to do it. Not the one at Releases but Actions>Release v0.7 debug

Then use Xposed Disable Flag Secure normally
