### ISSUE TITLE
yonder app

### ISSUE THREAD

**Issue by whtcryn** [VarunS2002/Xposed-Disable-FLAG_SECURE#23]
please try to apply this to yonder app. that'd be very helpful. thank you.

**Comment by VarunS2002** [comment]
@whtcryn 
Sorry for the very late reply. I have been very busy.
What is the exact issue here?

It allows you to screenshot but the image is black.
It does not allow you to take a screenshot at all.

**Comment by whtcryn** [comment]
that's okay. 

it doesn't let me screenshot at all. i have to use scrpcy but the quality's not on par & was wondering if you'd examine on the yonder app. 

i use miui which might be the reason too. anyways, thanks.

**Comment by VarunS2002** [comment]
@whtcryn 
I will look into it in my free time.

**Comment by VarunS2002** [comment]
@whtcryn Are you using LSPatch?

**Comment by whtcryn** [comment]
along with shizuku, i did use lspatch but didn't work

**Comment by VarunS2002** [comment]
> along with shizuku, i did use lspatch but didn't work

So this module hooks into Android system and the target app to remove the restrictions. For many apps, just hooking into the targeted app is required (which is what LSPatch does) but for some apps (eg. WhatsApp), you need to hook into Android System too which LSPatch cannot do and needs root (afaik). There is nothing I can do about this.

**Comment by whtcryn** [comment]
that's alright. thanks for explaining
