### ISSUE TITLE
Not working for Snapchat

### ISSUE THREAD

**Issue by realcatgirly** [VarunS2002/Xposed-Disable-FLAG_SECURE#7]
As of the latest updates, Snapchat sets FLAG_SECURE upon exiting to multitasking, thus preventing secret screenshots from launcher screenshot features. 
LSPosed and this module with Systemframework, Snapchat and the Launcher selected as scope isn't able to bypass this.

**Comment by VarunS2002** [comment]
@tomjschwanke Yes I noticed this and Snap is not the only app, even Google Camera does the same thing recently. However, it doesn't look like they are using FLAG_SECURE since there are many methods of changing the image on the overview screen. If they are using any other Android flag then it might be possible to override using a different Xposed module. If they are using any native solution then it could be complicated to handle.

**Comment by realcatgirly** [comment]
@VarunS2002 Hmm I was thinking it's FLAG_SECURE since the launcher says "this app or your organization does not allow screenshots in this app", which is the same as FLASH_SECURE

**Comment by VarunS2002** [comment]
@tomjschwanke Oh really? Try enabling the module for the launcher too.

**Comment by realcatgirly** [comment]
@VarunS2002 that's what I did but it didn't help

**Comment by VarunS2002** [comment]
@tomjschwanke Well that's unfortunate. Try opening an issue [here](https://github.com/LSPosed/DisableFlagSecure) too. I don't have the time to work on this right now and I also don't have Snap.

**Comment by VarunS2002** [comment]
@tomjschwanke 
Which launcher do you use?
And can you share the Xposed log here too.

**Comment by VarunS2002** [comment]
> @VarunS2002 Hmm I was thinking it's FLAG_SECURE since the launcher says "this app or your organization does not allow screenshots in this app", which is the same as FLASH_SECURE

@tomjschwanke  
I had this tested through a proxy but Snap allows to take a screenshot from the overview, it's just black (which is something I cannot handle as I told earlier)
My test:

![flag_secure snapchat](https://user-images.githubusercontent.com/30069380/135722358-fe74334b-6d8f-4d82-bbcd-1613f376ea53.jpg)
