### ISSUE TITLE
now screenshots don't work for me anywhere anymore

### ISSUE THREAD

**Issue by SmellsGoood** [VarunS2002/Xposed-Disable-FLAG_SECURE#8]
Since I've downloaded the LSPosed module and activated it, I can't take any more screenshots at all, but I don't want to have to reset my mobile phone, there is another one Possibility to solve the problem?

**Comment by VarunS2002** [comment]
@SmellsGoood What do you mean screenshots don't work anywhere anymore?

**Comment by VarunS2002** [comment]
@SmellsGoood 
This issue will be closed in 2 days due to inactivity
