### ISSUE TITLE
Bug in educatio app

### ISSUE THREAD

**Issue by xMA3x** [VarunS2002/Xposed-Disable-FLAG_SECURE#9]
So I has tested the module in an education app which called educatio

And the bug is:
After activating the module to the application, the application don't lunche!
It just opens for a second and then close again

Which is very weird because I tested the mould on Netflix and it worked fine!

Here is the link of the app if you want to test:
https://play.google.com/store/apps/details?id=com.kadrma.educatio

Notice:
API version
93

Injection Interface
Riru

Framework version
1.6.3 (6212)

Manager version
1.6.3 (6212)

System version
12 (API 31)

Device
Realme RMX1851 

System ABI
arm64-v8a

The background of the app if anyone interested:
It's an app that provides courses for my collage, I pay for it and they give me only 2 chance to watch the lecture Wich is unfair, I wanna to record what is mine, helping me with a quick fix or something will be very useful

**Comment by VarunS2002** [comment]
@xMA3x 
Seems to be a bug with Educatio.
Did you try
1. Opening the App
2. Switching to Xposed and Activating the module on it
3. Switching back to the app and trying to record

**Comment by xMA3x** [comment]
I just tried that and no it didn't work, it gives me black screen

**Comment by VarunS2002** [comment]
@xMA3x
I have listed 3 alternative apps here: https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE#note
Try if any one of those work for you

**Comment by xMA3x** [comment]
I have tried all of them, And they gives the same result, the app close after being lunched

**Comment by VarunS2002** [comment]
@xMA3x Then it's probably a bug with the app itself or a protective measure I cannot bypass :(
